[szurubooru]
login = "user"
password = "password"
url = "https://example.com/"

[a1111_point]
login = "user"
password = "password"
url = "http://127.0.0.1:7860/"

[comfy_point]
token = "token"
url = "http://127.0.0.1:7860/"

[danbooru]
login = "user"
token = ""
url = "https://example.com/"